version: '3'
services:

 mysql:
  image: mysql:5.5
  network_mode: host
  restart: always
  ports:
   - "3306:3306"

  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: moviedb
   MYSQL_USER: root12
   MYSQL_PASSWORD: root12

 spring:
  image: spring-image-services
  build: backend/
  restart: always
  network_mode: host
  ports:
   - "8082:8082"
  expose:
   - "8800"
  depends_on:
   - mysql

 angular:
  image: angular-image
  build: frontend/
  network_mode: host
  container_name: angular-docker
  ports:
   - "4200:4200"
   
 user-app: 
    build: moviecruiserauthenticationservices/
    depends_on: 
      - mysql
    expose: 
      - 2244
    image: movie-user-app
    network_mode: host
    ports: 
      - "2244:2244"
    restart: always
  
